### ISSUE TITLE
WooCommerceAPI is returning wrong endpoint information

### ISSUE THREAD

**Issue by murdockcrc** [woothemes/wc-api-node#1]
I am using nodejs SDK v1.0.2. When I try to read the endpoint index, I just get a `1` result:

    _wooHelper.get('', function(error, data, res){
	console.log(res);
	done();
    });

`console.log(res)` outputs `1`. Inspecting the `data` variable, it looks like the client is connecting to `/wc-api/v3`. Connecting to this url via curl also returns 1. Connecting via curl to `/wc-api/v2` does return the expected index information.

I wanted to submit an issue as I am not sure if the result `1` when connecting to `v3` is by design, and I am not sure how to tell the nodejs sdk woocommerce api client to instead connect to `v2` and get the correct endpoint information.

**Comment by claudiosmweb** [comment]
Here is not a support channel and It's clear that you did not read any docs before trying test!
