### ISSUE TITLE
Throwing "write EPROTO" error in case of SSL.

### ISSUE THREAD

**Issue by sayeed123** [woothemes/wc-api-node#10]
We are facing "write EPROTO"  error for now, initially it was working for non-ssl.
In case of ssl, we are not able to access woocommerce api in node.My woocomerce application is running on ssl, while node is not running on ssl.

     Error: write EPROTO 140336970151808:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

Please take a look and assist us to resolve this issue.

Thanks

**Comment by claudiosmweb** [comment]
Seems to be an error on your environment, maybe a old version of OpenSSL.
Don't seems to have any error in this wrapper.

**Comment by EmilyFranklin** [comment]
I got a very similar error because specified the wrong port. I specified it to be 80 but it should have been 443 or not specified. I'm not sure exactly what the issue is here but that might be part of it.
