### ISSUE TITLE
Consumer Secret is invalid

### ISSUE THREAD

**Issue by samarthagarwal** [woothemes/wc-api-node#12]
I am trying to get data from my Woocommerce store. The store is located at an 'https' url but all get in the response to any endpoint is,

`{
errors: [
{
code: "woocommerce_api_authentication_error",
message: "Consumer Secret is invalid"
}
]
}`

I have generated and cross checked the key and secret multiple times. I can get the data in the browser if I send credentials as query params but not using the API.
What is wrong?

**Comment by samarthagarwal** [comment]
Addition: I have tried my NodeJS code with another Woocommerce store which has a `http` url and it works fine.

**Comment by EehMauro** [comment]
Same problem, I've a store with `https` too.

**Comment by claudiosmweb** [comment]
Closed in favor of #8

**Comment by albahac** [comment]
@samarthagarwal  Did you finally find  the right way to modify this? help please

**Comment by samarthagarwal** [comment]
@albahac set `queryStringAuth` option, just set as true.
