### ISSUE TITLE
woocommerce_api_authentication_error, Invalid Timestamp

### ISSUE THREAD

**Issue by luandro** [woothemes/wc-api-node#16]
I'm working on a local Wordpress server and a local NodeJS server. 

Everything was working fine until I changed some products on Woocommerce, and I started getting this error when trying to call the API.

```
{
  errors: [
    {
      code: "woocommerce_api_authentication_error",
      message: "Timestamp inválido"
    }
  ]
}
```

**Comment by claudiosmweb** [comment]
It does not seem to be an issue with this REST API wrapper.
Maybe it's cache, try to clear the entire cache of your WordPress, but this is not the right place to ask for support not related to this wrapper.
