### ISSUE TITLE
Create customer leaves WP user with email address as default display name

### ISSUE THREAD

**Issue by murdockcrc** [woothemes/wc-api-node#2]
(Perhaps this is more an enhancement request)

We can successfully create a customer account on wordpress from our nodejs backend (as documented in http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-customer).

However, we have noted that, once the customer account is created, the user's default public display name is set to the email address (we need users to login with their email addresses). We are setting the user's first and last name properties during user creation, as this:
    
	var newCustomer = {
		customer: {
	    email: _this.email,
        first_name: _this.firstName,
        last_name: _this.lastName,
	    username: _this.email,
	    password: _this.password,
	  }
	
	_wooHelper.post('customers', newCustomer, callback);
    
I am not entirely sure if setting the public display name is within WooCommerce's API control or not, but just wanted to report this to the dev team and see if this is a dead-end or a potential enhancement to the nodejs client.

**Comment by claudiosmweb** [comment]
This is not an issue with this wrapper.
Please use this repository to report bugs or anything related with THIS wrapper!
