### ISSUE TITLE
Customizable api path 

### ISSUE THREAD

**Issue by enricodeleo** [woothemes/wc-api-node#22]
Since wp-rest allow the developer to change the default path (for example I use wp-rest instead of wp-json) the module should provide a way to specify so.

**Comment by claudiosmweb** [comment]
What module?
We use the WP REST API, if you can change it, so you can change on WooCommerce too.

**Comment by enricodeleo** [comment]
This module, `wc-api-node` has the basepath hardcoded if you set wpApi to true it assigns `wp-json` as base path for the endpoint, in my opinion you should make it customizable, like `wpApi: 'wp-rest'`

**Comment by claudiosmweb** [comment]
@enricodeleo you can use any other wrapper.

**Comment by enricodeleo** [comment]
I know, but I think that this module could cover this possibility. I made a pull request about it, feel free to discard it if you think it is not useful.

A lot of developers customized the url prefix since it was a required step if you had the v1 version of wp rest api and you had to run both concurrently during the migration (see https://make.wordpress.org/core/2015/04/29/wp-rest-api-version-2-0-beta-1/)

**Comment by claudiosmweb** [comment]
Solved with #24
