### ISSUE TITLE
WooCommerce api not working in nodejs

### ISSUE THREAD

**Issue by prdpsngh05** [woothemes/wc-api-node#35]
Hello ,
I have implemented woocommerce api in my nodejs project. i have implemented this from https://www.npmjs.com/package/woocommerce-api.
but its always returns garbage values(html ) in response. can you provide any suppoert for this?
Thanks

**Comment by claudiosmweb** [comment]
Don't seems to be an issue with this wrapper.
If you need help with WooCommerce, you should use the support forum: https://wordpress.org/support/plugin/woocommerce
