### ISSUE TITLE
PUT request removing product categories on update

### ISSUE THREAD

**Issue by seigneur** [woothemes/wc-api-node#36]
When I try to update the price, the price updates and all other fields are intact, except the categories, which becomes null.

```
wooCommerce.get('/products/'+prodid, function(err, pdata, res) {
pdata.product.regular_price = newPrice
//here categories is ["Category 1"]
wooCommerce.put('/products/'+prodid, pdata, function(err, data, res) {
					console.log(err, 'res' ,res.body);
                    //here category is []
				})
})
```

Is there something simple that I missed?

**Comment by claudiosmweb** [comment]
Don't seems to be an issue with this wrapper.
If you need help with WooCommerce, you should use the support forum: https://wordpress.org/support/plugin/woocommerce
