### ISSUE TITLE
Authentication fails when path is not wc/vXXX

### ISSUE THREAD

**Issue by luciancapdefier** [woothemes/wc-api-node#37]
Hi, I am struggling a lot with auth in case the vendor is changed to something else than wc.

var WooCommerce = new WooCommerceAPI({
	url: 'http://store.com',
	consumerKey: 'ck_XXX',
	consumerSecret: 'cs_XXX',
	verifySsl: false,
	wpAPI: true,
	version: '**vendorA**/v1',
	queryStringAuth: true,
});

permission_callback will call wc_rest_check_manager_permissions() or connected_user_can() which no longer finds the permissions of the user used in the connection.

Please clarify if this is the expected behaviour or I am missing something.

Thx,

**Comment by claudiosmweb** [comment]
Not an issue with this wrapper.
And it's a expected behavior, the authentication methods for WooCommerce will works only if the vendor is `wc` or `wc-`.
