### ISSUE TITLE
No route was found matching the URL and request method

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/wc-api-node#4]
@claudiosmweb while I was testing for this example got error. Is there anything I was missing:

```js
// PUT example
WooCommerce.put('orders', { // Working if orders/id. IMO this should be updated in example
  order: {
    status: 'completed'
  }
}, function(err, data, res) {
  console.log(res);
});
```

This return *No route was found matching the URL and request method*
```bash
{"errors":[{"code":"woocommerce_api_no_route","message":"No route was found matching the URL and request method"}]}
```

**Comment by claudiosmweb** [comment]
Yep, missing two things:

1. Read the documentation: http://woothemes.github.io/woocommerce-rest-api-docs/#update-an-order
2. The order ID, what order are you trying update? :p
