### ISSUE TITLE
just can't give any information "undefined"

### ISSUE THREAD

**Issue by ayzakh** [woothemes/wc-api-node#6]
![screenshot from 2015-12-08 02 36 55](https://cloud.githubusercontent.com/assets/9413058/11634587/61f6d6f0-9d4c-11e5-8f0e-8d5ef407037b.png)
![screenshot from 2015-12-08 02 39 00](https://cloud.githubusercontent.com/assets/9413058/11634603/7d71356a-9d4c-11e5-8a64-848911f2378e.png)
![screenshot from 2015-12-08 02 39 46](https://cloud.githubusercontent.com/assets/9413058/11634617/96a2b324-9d4c-11e5-91f3-80388f59dbb5.png)
![screenshot from 2015-12-08 02 43 36](https://cloud.githubusercontent.com/assets/9413058/11634725/2e66be94-9d4d-11e5-8b3b-85a365841968.png)
![screenshot from 2015-12-08 02 43 45](https://cloud.githubusercontent.com/assets/9413058/11634724/2e645c3a-9d4d-11e5-8164-be2c82916b8a.png)

**Comment by claudiosmweb** [comment]
Check the `error` and `data`.
Seems like have some error on it.

**Comment by ayzakh** [comment]
whole the variables looks like 'undefined'
console.log(' Result: ' + res + ' data: ' + data + ' res: ' + res);
// Result: undefined data: undefined res: undefined

**Comment by ayzakh** [comment]
console.log(' err: ' + err + ' data: ' + data + ' res: ' + res);
// err: Error: getaddrinfo ENOTFOUND wordpress.localhost wordpress.localhost:80 data: undefined res: undefined

**Comment by ayzakh** [comment]
which dependency have this problem?

**Comment by claudiosmweb** [comment]
@ayzakh So there the error you must correct in your environment:

> Error: getaddrinfo ENOTFOUND wordpress.localhost wordpress.localhost:80

**Comment by ayzakh** [comment]
I solved this problem. The problem was in /etc/hosts file. Thanks.

**Comment by claudiosmweb** [comment]
;)
