### ISSUE TITLE
Fields Parameter does not work as expected

### ISSUE THREAD

**Issue by cyxou** [woothemes/wc-api-node#7]
As [documentation states](http://woothemes.github.io/woocommerce-rest-api-docs/?javascript#parameters), we may limit the fields returned in the response using the fields parameter like this `GET /orders?fields=id`. This pretty much works with *orders* endpoint, but returns strange results when using with *customers/\<id\>/orders* endpoint. For example:

`customers/405/orders?fields=order_number,completed_at,line_items` returns single cancelled order, whereas with only `customers/405/orders` it returns all processed user's orders without any cancelled ones.

Could you please investigate on this issue?

PS. I'm using woocommerce-api v1.0.4 and did not specify api version in the WooCommerceAPI constuctor, thus it is supposed to be v3.

**Comment by claudiosmweb** [comment]
Not an issue in this REST API wrapper. Maybe can be on WooCommerce. But here is not the right place for report WooCommerce issues.
