### ISSUE TITLE
Query string authentication fallback

### ISSUE THREAD

**Issue by Ramblurr** [woothemes/wc-api-node#8]
Hi,
On some hosts the basic authentication method doesn't work (Dreampress's Varnish cache for example, strips the authorization header).

The WC API already has a query parameter fallback (e.g., `&consumer_key=ck_...&consumer_secret=cs_...`), could this get exposed in the Node api as an option?

**Comment by claudiosmweb** [comment]
Submit a Pull Request.

**Comment by claudiosmweb** [comment]
Added new `queryStringAuth` option, just set as `true`.
