### ISSUE TITLE
can't delete a shipping class, getting error code "woocommerce_api_no_route"

### ISSUE THREAD

**Issue by AlaaSelim** [woothemes/wc-api-node#9]
i'm using this code:
`   WooCommerce.delete('products/shipping_class/27', function(err, data, res) {
          console.log(res);
   });
`
and keep getting this error:

`{"errors":[{"code":"woocommerce_api_no_route","message":"No route was found matching the URL and request method"}]}`

i have tried on 2 different sites ( and changed the class id number) and same error keep showing up.

i can do other operations like get and put successfully.

**Comment by claudiosmweb** [comment]
![screenshot from 2016-02-11 23-43-44](https://cloud.githubusercontent.com/assets/1264099/12996696/4fb64772-d119-11e5-8d55-5147fed4e8c0.png)

Note the warning saying "Endpoint introduced since WooCommerce 2.5."

**Comment by claudiosmweb** [comment]
Typo in the documentation.

Use:

```js
WooCommerce.delete('products/shipping_classes/27', function(err, data, res) { console.log(res); });
```
